init_lr: 0.001
lr_decay_gamma: 0.37425082035224766
beta: 8
tv_reg: 1.7925542621817476e-05
batch_size: 8
loss_id: mae
k: 8
n_tbins: 1024
epochs: 50
recon: zncc
peak_reg: null
beta_max: 8

dataset:
  sigma: 10
  num_samples: 2
  irf_filename: null
  account_irf: false
  account_illum: false
  grid_size: 10
  minmax_counts : [100, 3000]
  minmax_sbrs: [0.1, 5.0]
  peak_factor : 0.03
  start_bin: 3
  end_bin: 3


model_params:
  learn_illum: false
  learn_coding_mat : true

  init_illum: learned_codes/bandlimited_peak_models/n1024_k8_sigma10_peak015_counts1000/illum_model.npy
  init_coding_mat: null
