init_lr: 0.0018
lr_decay_gamma: 0.37425082035224766
beta: 8
tv_reg: 1.7925542621817476e-05
batch_size: 8
loss_id: mae
k: 8
n_tbins: 1024
epochs: 50
recon: zncc
peak_reg: null
beta_max: 8

dataset:
  sigma: 10
  num_samples: 15000
  irf_filename: null
  account_irf: false
  account_illum: false
  grid_size: 10
  minmax_counts : [1000, 1000]
  minmax_sbrs: [0.1, 10.0]
  peak_factor : 0.015
  start_bin: 3
  end_bin: 3


model_params:
  learn_illum: true
  learn_coding_mat : true

  init_illum: null
  init_coding_mat: null
