init_lr: 0.0009145173790926249
lr_decay_gamma: 0.31228240706108457
beta: 8
beta_max: 8
tv_reg: 0.09723338742824626
peak_reg: 20
batch_size: 8
loss_id: mae
recon: zncc
k: 4
n_tbins: 1024
epochs: 50


dataset:
  sigma: 10
  num_samples: 4661
  grid_size: 10
  minmax_counts : [1000, 1000]
  minmax_sbrs: [0.1, 10.0]
  peak_factor : 0.03

model_params:
  learn_illum: true
  learn_coding_mat : true

  init_illum: null
  init_coding_mat: null