batch_size: 24
beta: 8
epochs: 100
k: 4
n_tbins: 1024
init_lr: 0.001
lr_decay_gamma: 0.9
num_samples: 4661
tv_reg: 0.09723338742824626
loss_id: mae


dataset:
  sigma: 30
  num_samples: 4661
  grid_size: 10
  minmax_counts : [10, 100]
  minmax_sbrs: [1, 15]
