batch_size: 24
beta: 8
epochs: 100
k: 4
n_tbins: 1024
init_lr: 0.0009145173790926249
lr_decay_gamma: 0.37425082035224766
tv_reg: 0.09723338742824626
loss_id: mae
recon: zncc

dataset:
  sigma: 30
  num_samples: 4661
  irf_filename: null
  account_irf: true
  account_illum: false
  grid_size: 10
  minmax_counts : [100, 5000]
  minmax_sbrs: [0.1, 5.0]
  start_bin: 3
  end_bin: 3

model_params:
  learn_illum: true
  learn_coding_mat : true

  init_illum: null
  init_coding_mat: null