beta: 8
batch_size: 8
epochs: 50
init_lr: 0.0013555721642207629
k: 8
loss_id: rmse
lr_decay_gamma: 0.31228240706108457
n_tbins: 2188
recon: zncc
sigma: None
tv_reg: 1.7925542621817476e-05

dataset:
  account_illum: false
  account_irf: false
  end_bin: 3
  grid_size: 10
  irf_filename: irf/irf_tres-8ps_tlen-17504ps.npy
  minmax_counts:
  - 100
  - 2000
  minmax_sbrs:
  - 0.5
  - 5.0
  num_samples: 30000
  sigma: None
  start_bin: 3

model_params:
  init_coding_mat: null
  init_illum: true
  learn_coding_mat: true
  learn_illum: false