dataset:
  account_irf: false
  account_illum: false
  end_bin: 3
  grid_size: 10
  irf_filename: irf/irf_tres-8ps_tlen-17504ps.npy
  minmax_counts:
  - 500
  - 5000
  minmax_sbrs:
  - 0.5
  - 5.0
  num_samples: 15000
  sigma: None
  start_bin: 3

epochs: 50
init_lr: 0.013555721642207629
irf_filename: 
k: 8
loss_id: mae
lr_decay_gamma: 0.31228240706108457
beta: 8
batch_size: 8
n_tbins: 2188
recon: zncc
tv_reg: 1.7925542621817476e-05


model_params:
  init_coding_mat: null
  init_illum: null
  learn_coding_mat: true
  learn_illum: true


