init_lr: 0.013
lr_decay_gamma: 0.31228240706108457
beta: 8
tv_reg: 1.7925542621817476e-05
batch_size: 8
loss_id: mae
k: 8
n_tbins: 8196
epochs: 100
recon: zncc

dataset:
  sigma: 200
  irf_filename: null
  account_irf: false
  account_illum: false
  num_samples: 50000
  grid_size: 10
  minmax_counts : [100, 4000]
  minmax_sbrs: [0.1, 5.0]
  start_bin: 3
  end_bin: 3


model_params:
  learn_illum: true
  learn_coding_mat : true

  init_illum: true
  init_coding_mat: null
